#! /usr/bin/env python
from __future__ import division,print_function
import argparse
from modular_client import ModularClient


def main():
    parser = argparse.ArgumentParser(description='Save api from a Modular device.')
    parser.add_argument('-p','--port',help='Modular device port.')
    args = parser.parse_args()

    if args.port is not None:
        print("Opening modular client on port {0}...".format(args.port))
    else:
        print("Attempting to find modular device...")

    dev = ModularClient(port=args.port)
    print("Modular device {0} found on port {1}".format(dev.get_device_id(),dev.get_port()))
    print("Saving api...")
    dev.save_api()

if __name__ == '__main__':
    main()

