#! /usr/bin/env python
from __future__ import division, print_function
import os
from jinja2 import Environment, FileSystemLoader


api_dir = './api/'

def main():
    api_array = []
    try:
        api_array = os.listdir(api_dir)
    except OSError:
        pass
    if len(api_array) > 0:
        print('API found: {0} in {1}'.format(api_array,api_dir))
    else:
        print('No API found in {0}! Connect modular device and run save_device_api.'.format(api_dir))
        return
    env = Environment(
        loader=FileSystemLoader('./templates'),
    )
    cmake_template = env.get_template('CMakeLists.txt')
    print(cmake_template.render())

if __name__ == '__main__':
    main()

